apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 1m0s
  chart:
    spec:
      chart: grafana
      version: "6.60.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    adminUser: admin
    adminPassword: admin  # TODO: Change this in production!
    service:
      type: NodePort
