apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: default
spec:
  chart:
    spec:
      chart: nginx
      version: 1.2.3
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
