apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx
  namespace: default
spec:
  interval: 1m0s  # Reconcile every 1 minute
  chart:
    spec:
      chart: nginx
      version: 13.2.15
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    replicaCount: 1
    service:
      type: ClusterIP
